-- MySQL Script generated by MySQL Workbench
-- Thu Jun 26 22:47:57 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_gest_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_gest_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_gest_project` DEFAULT CHARACTER SET utf8 ;
USE `bd_gest_project` ;

-- -----------------------------------------------------
-- Table `bd_gest_project`.`filieres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_gest_project`.`filieres` (
  `id_filiere` INT NOT NULL AUTO_INCREMENT,
  `libelle_filiere` VARCHAR(50) NOT NULL,
  `description_filiere` VARCHAR(255) NULL,
  PRIMARY KEY (`id_filiere`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_gest_project`.`etudiants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_gest_project`.`etudiants` (
  `Id_etudiant` INT NOT NULL AUTO_INCREMENT,
  `nom_etudiant` VARCHAR(50) NOT NULL,
  `Prenom_etudiant` VARCHAR(50) NOT NULL,
  `age` INT NOT NULL,
  `date_naissance` DATE NOT NULL,
  `filiere` INT NOT NULL,
  `date_inscription` DATE NULL,
  `photo_profil` BLOB NULL,
  PRIMARY KEY (`Id_etudiant`),
  INDEX `fk_filiere_etudiant_idx` (`filiere` ASC) VISIBLE,
  CONSTRAINT `fk_filiere_etudiant`
    FOREIGN KEY (`filiere`)
    REFERENCES `bd_gest_project`.`filieres` (`id_filiere`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_gest_project`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_gest_project`.`roles` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `libelle_role` VARCHAR(50) NOT NULL,
  `description_role` VARCHAR(255) NULL,
  PRIMARY KEY (`id_role`),
  UNIQUE INDEX `libelle_role_UNIQUE` (`libelle_role` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_gest_project`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_gest_project`.`utilisateurs` (
  `ud_utilisateur` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` INT NOT NULL,
  `photo_profil` BLOB NULL,
  PRIMARY KEY (`ud_utilisateur`),
 INDEX `role_UNIQUE` (`role` ASC),
  CONSTRAINT `fk_role_utilisateur`
    FOREIGN KEY (`role`)
    REFERENCES `bd_gest_project`.`roles` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_gest_project`.`gestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_gest_project`.`gestion` (
  `id_gestion` INT NOT NULL AUTO_INCREMENT,
  `id_utilisateur` INT NOT NULL,
  `id_etudiant` INT NOT NULL,
  `action` ENUM('Creation', 'Modification', "Suppression") NOT NULL,
  `date_gestion` DATE NOT NULL,
  PRIMARY KEY (`id_gestion`),
  INDEX `fk_utilisateur_etudiant_action_idx` (`id_utilisateur` ASC) VISIBLE,
  INDEX `fk_etudiant_utilisateur_action_idx` (`id_etudiant` ASC) VISIBLE,
  CONSTRAINT `fk_utilisateur_etudiant_action`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `bd_gest_project`.`utilisateurs` (`ud_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etudiant_utilisateur_action`
    FOREIGN KEY (`id_etudiant`)
    REFERENCES `bd_gest_project`.`etudiants` (`Id_etudiant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
